title: Curriculum vitae of Máté Hegyháti, PhD
email: hegyhati.work@gmail.com
description: > 
  Curriculum vitae, list of publications, etc. for Mate Hegyhati.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hegyhati.info" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


